In [15]:
from pandas_datareader import data
import datetime
import yfinance as yf
from bokeh.plotting import figure, show, output_file


start=datetime.datetime(2019,10,1)
end=datetime.datetime(2019,10,31)

df=data.DataReader(name="AAPL",data_source="yahoo",start=start,end=end)
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2019-10-01,228.220001,224.199997,225.070007,224.589996,34805800,224.589996
2019-10-02,223.580002,217.929993,223.059998,218.960007,34612300,218.960007
2019-10-03,220.960007,215.130005,218.429993,220.820007,28606500,220.820007
2019-10-04,227.490005,223.889999,225.639999,227.009995,34619700,227.009995
2019-10-07,229.929993,225.839996,226.270004,227.059998,30576500,227.059998
2019-10-08,228.059998,224.330002,225.820007,224.399994,27955000,224.399994
2019-10-09,227.789993,225.639999,227.029999,227.029999,18692600,227.029999
2019-10-10,230.440002,227.300003,227.929993,230.089996,28253400,230.089996
2019-10-11,237.639999,232.309998,232.949997,236.210007,41698900,236.210007
2019-10-14,238.130005,234.669998,234.899994,235.869995,24106900,235.869995
2019-10-15,237.649994,234.880005,236.389999,235.320007,21840000,235.320007
2019-10-16,235.240005,233.199997,233.369995,234.369995,18475800,234.369995
2019-10-17,236.149994,233.520004,235.089996,235.279999,16896300,235.279999
2019-10-18,237.580002,234.289993,234.589996,236.410004,24358400,236.410004
2019-10-21,240.990005,237.320007,237.520004,240.509995,21811800,240.509995
2019-10-22,242.199997,239.619995,241.160004,239.960007,20573400,239.960007
2019-10-23,243.240005,241.220001,242.100006,243.179993,18957200,243.179993
2019-10-24,244.800003,241.809998,244.509995,243.580002,17318800,243.580002
2019-10-25,246.729996,242.880005,243.160004,246.580002,18330500,246.580002
2019-10-28,249.250000,246.720001,247.419998,249.050003,24112500,249.050003
2019-10-29,249.750000,242.570007,248.970001,243.289993,35660100,243.289993
2019-10-30,245.300003,241.210007,244.759995,243.259995,30950600,243.259995
2019-10-31,249.169006,243.259995,247.240005,247.649994,22637848,247.649994

In [46]:
def market(c,o):
    if c > o:
        value="Bull"
    elif c < o: 
        value="Bear"
    else:
        value="Equal"
    return value

df["Status"]=[market(c,o) for c, o in zip(df.Close,df.Open)]
df.drop("status",axis=1)

,High,Low,Open,Close,Volume,Adj Close,Status
Date,,,,,,,
2019-10-01,228.220001,224.199997,225.070007,224.589996,34805800,224.589996,Bear
2019-10-02,223.580002,217.929993,223.059998,218.960007,34612300,218.960007,Bear
2019-10-03,220.960007,215.130005,218.429993,220.820007,28606500,220.820007,Bull
2019-10-04,227.490005,223.889999,225.639999,227.009995,34619700,227.009995,Bull
2019-10-07,229.929993,225.839996,226.270004,227.059998,30576500,227.059998,Bull
2019-10-08,228.059998,224.330002,225.820007,224.399994,27955000,224.399994,Bear
2019-10-09,227.789993,225.639999,227.029999,227.029999,18692600,227.029999,Equal
2019-10-10,230.440002,227.300003,227.929993,230.089996,28253400,230.089996,Bull
2019-10-11,237.639999,232.309998,232.949997,236.210007,41698900,236.210007,Bull
2019-10-14,238.130005,234.669998,234.899994,235.869995,24106900,235.869995,Bull
2019-10-15,237.649994,234.880005,236.389999,235.320007,21840000,235.320007,Bear
2019-10-16,235.240005,233.199997,233.369995,234.369995,18475800,234.369995,Bull
2019-10-17,236.149994,233.520004,235.089996,235.279999,16896300,235.279999,Bull
2019-10-18,237.580002,234.289993,234.589996,236.410004,24358400,236.410004,Bull
2019-10-21,240.990005,237.320007,237.520004,240.509995,21811800,240.509995,Bull
2019-10-22,242.199997,239.619995,241.160004,239.960007,20573400,239.960007,Bear
2019-10-23,243.240005,241.220001,242.100006,243.179993,18957200,243.179993,Bull
2019-10-24,244.800003,241.809998,244.509995,243.580002,17318800,243.580002,Bear
2019-10-25,246.729996,242.880005,243.160004,246.580002,18330500,246.580002,Bull
2019-10-28,249.250000,246.720001,247.419998,249.050003,24112500,249.050003,Bull
2019-10-29,249.750000,242.570007,248.970001,243.289993,35660100,243.289993,Bear
2019-10-30,245.300003,241.210007,244.759995,243.259995,30950600,243.259995,Bear
2019-10-31,249.169006,243.259995,247.240005,247.649994,22637848,247.649994,Bull

In [47]:
df["Avg_price"]=(df.Open+df.Close)/2
df

,High,Low,Open,Close,Volume,Adj Close,status,Status,Avg_price
Date,,,,,,,,,
2019-10-01,228.220001,224.199997,225.070007,224.589996,34805800,224.589996,Bear,Bear,224.830002
2019-10-02,223.580002,217.929993,223.059998,218.960007,34612300,218.960007,Bear,Bear,221.010002
2019-10-03,220.960007,215.130005,218.429993,220.820007,28606500,220.820007,Bull,Bull,219.625000
2019-10-04,227.490005,223.889999,225.639999,227.009995,34619700,227.009995,Bull,Bull,226.324997
2019-10-07,229.929993,225.839996,226.270004,227.059998,30576500,227.059998,Bull,Bull,226.665001
2019-10-08,228.059998,224.330002,225.820007,224.399994,27955000,224.399994,Bear,Bear,225.110001
2019-10-09,227.789993,225.639999,227.029999,227.029999,18692600,227.029999,Equal,Equal,227.029999
2019-10-10,230.440002,227.300003,227.929993,230.089996,28253400,230.089996,Bull,Bull,229.009995
2019-10-11,237.639999,232.309998,232.949997,236.210007,41698900,236.210007,Bull,Bull,234.580002
2019-10-14,238.130005,234.669998,234.899994,235.869995,24106900,235.869995,Bull,Bull,235.384995
2019-10-15,237.649994,234.880005,236.389999,235.320007,21840000,235.320007,Bear,Bear,235.855003
2019-10-16,235.240005,233.199997,233.369995,234.369995,18475800,234.369995,Bull,Bull,233.869995
2019-10-17,236.149994,233.520004,235.089996,235.279999,16896300,235.279999,Bull,Bull,235.184998
2019-10-18,237.580002,234.289993,234.589996,236.410004,24358400,236.410004,Bull,Bull,235.500000
2019-10-21,240.990005,237.320007,237.520004,240.509995,21811800,240.509995,Bull,Bull,239.014999
2019-10-22,242.199997,239.619995,241.160004,239.960007,20573400,239.960007,Bear,Bear,240.560005
2019-10-23,243.240005,241.220001,242.100006,243.179993,18957200,243.179993,Bull,Bull,242.639999
2019-10-24,244.800003,241.809998,244.509995,243.580002,17318800,243.580002,Bear,Bear,244.044998
2019-10-25,246.729996,242.880005,243.160004,246.580002,18330500,246.580002,Bull,Bull,244.870003
2019-10-28,249.250000,246.720001,247.419998,249.050003,24112500,249.050003,Bull,Bull,248.235001
2019-10-29,249.750000,242.570007,248.970001,243.289993,35660100,243.289993,Bear,Bear,246.129997
2019-10-30,245.300003,241.210007,244.759995,243.259995,30950600,243.259995,Bear,Bear,244.009995
2019-10-31,249.169006,243.259995,247.240005,247.649994,22637848,247.649994,Bull,Bull,247.445000

In [51]:
df["Height"]=abs(df.Open-df.Close)
df

,High,Low,Open,Close,Volume,Adj Close,status,Status,Avg_price,Height
Date,,,,,,,,,,
2019-10-01,228.220001,224.199997,225.070007,224.589996,34805800,224.589996,Bear,Bear,224.830002,0.480011
2019-10-02,223.580002,217.929993,223.059998,218.960007,34612300,218.960007,Bear,Bear,221.010002,4.099991
2019-10-03,220.960007,215.130005,218.429993,220.820007,28606500,220.820007,Bull,Bull,219.625000,2.390015
2019-10-04,227.490005,223.889999,225.639999,227.009995,34619700,227.009995,Bull,Bull,226.324997,1.369995
2019-10-07,229.929993,225.839996,226.270004,227.059998,30576500,227.059998,Bull,Bull,226.665001,0.789993
2019-10-08,228.059998,224.330002,225.820007,224.399994,27955000,224.399994,Bear,Bear,225.110001,1.420013
2019-10-09,227.789993,225.639999,227.029999,227.029999,18692600,227.029999,Equal,Equal,227.029999,0.000000
2019-10-10,230.440002,227.300003,227.929993,230.089996,28253400,230.089996,Bull,Bull,229.009995,2.160004
2019-10-11,237.639999,232.309998,232.949997,236.210007,41698900,236.210007,Bull,Bull,234.580002,3.260010
2019-10-14,238.130005,234.669998,234.899994,235.869995,24106900,235.869995,Bull,Bull,235.384995,0.970001
2019-10-15,237.649994,234.880005,236.389999,235.320007,21840000,235.320007,Bear,Bear,235.855003,1.069992
2019-10-16,235.240005,233.199997,233.369995,234.369995,18475800,234.369995,Bull,Bull,233.869995,1.000000
2019-10-17,236.149994,233.520004,235.089996,235.279999,16896300,235.279999,Bull,Bull,235.184998,0.190002
2019-10-18,237.580002,234.289993,234.589996,236.410004,24358400,236.410004,Bull,Bull,235.500000,1.820007
2019-10-21,240.990005,237.320007,237.520004,240.509995,21811800,240.509995,Bull,Bull,239.014999,2.989990
2019-10-22,242.199997,239.619995,241.160004,239.960007,20573400,239.960007,Bear,Bear,240.560005,1.199997
2019-10-23,243.240005,241.220001,242.100006,243.179993,18957200,243.179993,Bull,Bull,242.639999,1.079987
2019-10-24,244.800003,241.809998,244.509995,243.580002,17318800,243.580002,Bear,Bear,244.044998,0.929993
2019-10-25,246.729996,242.880005,243.160004,246.580002,18330500,246.580002,Bull,Bull,244.870003,3.419998
2019-10-28,249.250000,246.720001,247.419998,249.050003,24112500,249.050003,Bull,Bull,248.235001,1.630005
2019-10-29,249.750000,242.570007,248.970001,243.289993,35660100,243.289993,Bear,Bear,246.129997,5.680008
2019-10-30,245.300003,241.210007,244.759995,243.259995,30950600,243.259995,Bear,Bear,244.009995,1.500000
2019-10-31,249.169006,243.259995,247.240005,247.649994,22637848,247.649994,Bull,Bull,247.445000,0.409988

In [60]:
p=figure(x_axis_type="datetime", width=1000, height=300, sizing_mode="scale_width")
p.title.text="Apple"
p.grid.grid_line_alpha=0.65

p.segment(df.index,df.High,df.index,df.Low, color="black")

hours12=12*60*60*1000
p.rect(df.index[df.Status=="Bull"],df.Avg_price[df.Status=="Bull"],hours12,df.Height[df.Status=="Bull"], fill_color="green", line_color="black") 
p.rect(df.index[df.Status=="Bear"],df.Avg_price[df.Status=="Bear"],hours12,df.Height[df.Status=="Bear"], fill_color="red", line_color="black") 
p.rect(df.index[df.Status=="Equal"],df.Avg_price[df.Status=="Equal"],hours12,df.Height[df.Status=="Equal"], fill_color="black", line_color="black") 
output_file("CS.html")
show(p)